#!/bin/bash
######################################################################
# Install Development Data for Linux
######################################################################

# Get this script's location as the SvnHook directory.
svnhook_dir=$(dirname $(readlink -f $0))

# Define the indexed repository setup function.
function mkrepo {
    repo_num=$1
    repo_dir=repo_$repo_num
    repo_src=data/$repo_num/linux

    # Change into the test directory.
    cd "$svnhook_dir/SvnHook/test"

    # Construct the repository URL.
    repo_url=file://$(pwd)/$repo_dir
    echo "repo_url='$repo_url'"

    # If the test repository exists, remove it.
    if [[ -d $repo_dir ]]
    then
	echo "Removing old '$repo_dir' repository..."
	rm -rf $repo_dir
    fi

    # Create the test repository.
    echo "Creating new '$repo_dir' repository..."
    svnadmin create $repo_dir

    # Create the hook log directory.
    mkdir -v $repo_dir/logs

    # Copy the hook configuration files into the repository.
    find $repo_src -maxdepth 1 -name "*.xml" -type f \
	-exec cp -v {} $repo_dir/conf/ \;
    find $repo_src -maxdepth 1 -name "*-log.yml" -type f \
	-exec cp -v {} $repo_dir/conf/ \;
    find $repo_src -maxdepth 1 -name "*-log.conf" -type f \
	-exec cp -v {} $repo_dir/conf/ \;

    # Copy the hook scripts into the repository.
    for ascript in $repo_src/*.sh
    do
	ahook=$(basename $ascript | sed 's/\.sh$//')
	cp -v $ascript $repo_dir/hooks/$ahook
    done

    # Execute any initial Subversion commands.
    if [[ -f $repos_src/setup_svn.sh ]]
    then
	pushd $repos_src
	./setup_svn.sh $repo_url
	popd
    fi
}

# Set up the test repositories.
mkrepo 1

########################### end of file ##############################
